{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "echo-pong.fullname" . }}-default-deny
  labels:
    {{- include "echo-pong.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "echo-pong.fullname" . }}-allow-ingress
  labels:
    {{- include "echo-pong.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "echo-pong.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
{{- end }}
