apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-pong
  labels:
    app.kubernetes.io/name: echo-pong
    app.kubernetes.io/component: api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  rules:
    - host: echo-pong.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-pong
                port:
                  name: http
